### ISSUE TITLE
ERROR: current transaction is aborted

### ISSUE THREAD

**Issue by mbajur** [sunny/carrierwave-color#1]
Hello!

i'm trying to use that gem to store dominant color of uploaded image (obviously). It's probably the only gem available for that so i'm quite desperate to use it. The thing is, after doing everything just like described in the readme, after uploading a file, i'm getting:

```
ERROR: current transaction is aborted, commands ignored until end of transaction block
```

thrown by `Model.update` method in controller. I'm not sure what might be helpfull in here but that's almost clean model without any additional logic nor callbacks. The uploader looks like that:

``` rb
class PhotoUploader < CarrierWave::Uploader::Base
  include CarrierWave::Color
  include CarrierWave::MiniMagick

  storage :file

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  process quality: 85

  version :medium do
    process :resize_to_fill => [355, 252]
    process :store_dominant_color
  end

  def extension_white_list
    %w(jpg jpeg gif png)
  end

end
```

Thanks in advance for any help!

**Comment by mbajur** [comment]
It turned out that Miro is not working well with minimagick (or am i doing something wrong? I was not able to find anything about that).

**Comment by sunny** [comment]
Hi mbajur, thanks for submitting the issue! And thanks for solving it :)

The latest version of the gem does not use Miro anymore, so it might work better with your setup? (You would need to add `gem "carrierwave_color"` in your Gemfile and to rename your columns from `dominant_color_{attribute}` to `{attribute}_dominant_color`.)
