### ISSUE TITLE
Does it support png?

### ISSUE THREAD

**Issue by myriky** [sunny/carrierwave-color#4]
some png files doesn't process.
dominant color alway return nil.

has something issue?
thank you :)

**Comment by myriky** [comment]
i've figure why doesn't support.
because colorscore has some issue.

please check it out! 
https://github.com/quadule/colorscore/pull/7
:)

**Comment by sunny** [comment]
Thanks for looking into this issue and providing a PR! I'll make sur to update the `colorscore` dependency as soon as it is merged.
