### ISSUE TITLE
store_palette_color is throwing ArgumentError?

### ISSUE THREAD

**Issue by adamhowell** [sunny/carrierwave-color#6]
Hey there, thanks a lot for maintaining this gem!

I've been able to get `store_dominant_color` working, but when I tried to constrain the possible colors using `store_palette_color` per the docs like so

```
version :large_logo do
    # returns a 300x300 image
    process :resize_to_fill => [300, 300]
    process store_palette_color: ['F1453D', 'E62465', '9B2FAE']
end
```

 I get

`"ArgumentError (wrong number of arguments (given 3 expected 0..1)):"`

logo_palette_color is in my model. Thanks a lot for any help!

Adam

**Comment by sunny** [comment]
Hi Adam! Thanks for submitting this. Could you share a longer stacktrace to help me pinpoint what could trigger this?

Also, can you tell me what versions of `carrierwave-color` (e.g. 1.0.2) and `colorscore` (e.g. 0.0.5) you are using?

**Comment by sunny** [comment]
Ah! I think I understand! Can you try the following?

```rb
process store_palette_color: [['F1453D', 'E62465', '9B2FAE']]
```

There is another way of changing that palette color for your whole app:

```rb
Colorscore::Palette::DEFAULT = ['F1453D', 'E62465', '9B2FAE']
```

(However this will produce a warning since you are overwriting a constant and will not be supported and might end up not working anymore in future versions of carrierwave-color.)

**Comment by adamhowell** [comment]
Hey sunny, thanks a lot for the quick reply.

This worked perfectly!

`process store_palette_color: [['F1453D', 'E62465', '9B2FAE']]`

Thanks again for the help and for maintaining this gem. It's gonna make theming my little webapp based on the logo that's been uploaded so much nicer.

**Comment by sunny** [comment]
Woohoo! 🎉 I'm reopening the issue since the documentation is still wrong, and this could help people wondering the same thing as you.

PR #7 should fix it so that both notations (`[[…]]` and `[…]`) should work.
